# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Fri Jan 11 16:14:18 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(910, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/arduino.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.documentTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.documentTabWidget.setDocumentMode(True)
        self.documentTabWidget.setTabsClosable(True)
        self.documentTabWidget.setMovable(True)
        self.documentTabWidget.setObjectName(_fromUtf8("documentTabWidget"))
        self.gridLayout_4.addWidget(self.documentTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Project = QtGui.QMenu(self.menubar)
        self.menu_Project.setObjectName(_fromUtf8("menu_Project"))
        self.menuRecently_Opened = QtGui.QMenu(self.menu_Project)
        self.menuRecently_Opened.setObjectName(_fromUtf8("menuRecently_Opened"))
        self.menu_Build = QtGui.QMenu(self.menubar)
        self.menu_Build.setObjectName(_fromUtf8("menu_Build"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.projectTree = ProjectTree(self.dockWidgetContents_2)
        self.projectTree.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.projectTree.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.projectTree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.projectTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.projectTree.setAnimated(True)
        self.projectTree.setObjectName(_fromUtf8("projectTree"))
        self.gridLayout_3.addWidget(self.projectTree, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.consoleDockWidget = QtGui.QDockWidget(MainWindow)
        self.consoleDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.consoleDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.consoleDockWidget.setObjectName(_fromUtf8("consoleDockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stopBtn = QtGui.QToolButton(self.dockWidgetContents_3)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("process-stop"))
        self.stopBtn.setIcon(icon)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.gridLayout_2.addWidget(self.stopBtn, 1, 2, 1, 1)
        self.cleanConsoleBtn = QtGui.QToolButton(self.dockWidgetContents_3)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.cleanConsoleBtn.setIcon(icon)
        self.cleanConsoleBtn.setObjectName(_fromUtf8("cleanConsoleBtn"))
        self.gridLayout_2.addWidget(self.cleanConsoleBtn, 1, 3, 1, 1)
        self.consoleOut = QtGui.QTextEdit(self.dockWidgetContents_3)
        self.consoleOut.setUndoRedoEnabled(False)
        self.consoleOut.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.consoleOut.setReadOnly(True)
        self.consoleOut.setAcceptRichText(False)
        self.consoleOut.setObjectName(_fromUtf8("consoleOut"))
        self.gridLayout_2.addWidget(self.consoleOut, 0, 0, 1, 4)
        self.consoleDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.consoleDockWidget)
        self.searchDockWidget = QtGui.QDockWidget(MainWindow)
        self.searchDockWidget.setEnabled(True)
        self.searchDockWidget.setFloating(False)
        self.searchDockWidget.setObjectName(_fromUtf8("searchDockWidget"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.searchEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.searchEdit.setObjectName(_fromUtf8("searchEdit"))
        self.verticalLayout.addWidget(self.searchEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.replaceEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.replaceEdit.setObjectName(_fromUtf8("replaceEdit"))
        self.verticalLayout_2.addWidget(self.replaceEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.searchRegexp = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.searchRegexp.setObjectName(_fromUtf8("searchRegexp"))
        self.verticalLayout_3.addWidget(self.searchRegexp)
        self.searchCaseSensitive = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.searchCaseSensitive.setObjectName(_fromUtf8("searchCaseSensitive"))
        self.verticalLayout_3.addWidget(self.searchCaseSensitive)
        self.searchBack = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.searchBack.setObjectName(_fromUtf8("searchBack"))
        self.verticalLayout_3.addWidget(self.searchBack)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.searchBtn = QtGui.QPushButton(self.dockWidgetContents_5)
        self.searchBtn.setObjectName(_fromUtf8("searchBtn"))
        self.gridLayout.addWidget(self.searchBtn, 4, 0, 1, 1)
        self.replaceBtn = QtGui.QPushButton(self.dockWidgetContents_5)
        self.replaceBtn.setObjectName(_fromUtf8("replaceBtn"))
        self.gridLayout.addWidget(self.replaceBtn, 4, 1, 1, 1)
        self.searchDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.searchDockWidget)
        self.action_Build = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("run-build"))
        self.action_Build.setIcon(icon)
        self.action_Build.setObjectName(_fromUtf8("action_Build"))
        self.action_New = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_New.setIcon(icon)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_Save.setIcon(icon)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Save_As = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.action_Save_As.setIcon(icon)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.action_Exit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_Exit.setIcon(icon)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Clean = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("run-build-clean"))
        self.action_Clean.setIcon(icon)
        self.action_Clean.setObjectName(_fromUtf8("action_Clean"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Open_Project = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("project-open"))
        self.action_Open_Project.setIcon(icon)
        self.action_Open_Project.setObjectName(_fromUtf8("action_Open_Project"))
        self.action_Close = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-close"))
        self.action_Close.setIcon(icon)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_New_Project = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("project-development-new-template"))
        self.action_New_Project.setIcon(icon)
        self.action_New_Project.setObjectName(_fromUtf8("action_New_Project"))
        self.action_Upload = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("arrow-up-double"))
        self.action_Upload.setIcon(icon)
        self.action_Upload.setObjectName(_fromUtf8("action_Upload"))
        self.action_Serial_Monitor = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/connection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Serial_Monitor.setIcon(icon1)
        self.action_Serial_Monitor.setObjectName(_fromUtf8("action_Serial_Monitor"))
        self.action_Search = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find"))
        self.action_Search.setIcon(icon)
        self.action_Search.setObjectName(_fromUtf8("action_Search"))
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menuRecently_Opened.addSeparator()
        self.menu_Project.addAction(self.action_New_Project)
        self.menu_Project.addAction(self.action_Open_Project)
        self.menu_Project.addAction(self.menuRecently_Opened.menuAction())
        self.menu_Build.addAction(self.action_Build)
        self.menu_Build.addAction(self.action_Clean)
        self.menu_Help.addAction(self.action_About)
        self.menu_Tools.addAction(self.action_Serial_Monitor)
        self.menu_Edit.addAction(self.action_Search)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Project.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Build.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addAction(self.action_Save_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_New_Project)
        self.toolBar.addAction(self.action_Open_Project)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Build)
        self.toolBar.addAction(self.action_Clean)
        self.toolBar.addAction(self.action_Upload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Serial_Monitor)

        self.retranslateUi(MainWindow)
        self.documentTabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QIno - UI Interface for ino arduino tool", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Project.setTitle(QtGui.QApplication.translate("MainWindow", "&Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecently_Opened.setTitle(QtGui.QApplication.translate("MainWindow", "Recently Opened", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Build.setTitle(QtGui.QApplication.translate("MainWindow", "&Build", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop Process", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanConsoleBtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Clean Console", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanConsoleBtn.setText(QtGui.QApplication.translate("MainWindow", "Clean", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Search && Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.searchRegexp.setText(QtGui.QApplication.translate("MainWindow", "Regular Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCaseSensitive.setText(QtGui.QApplication.translate("MainWindow", "Case Sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBack.setText(QtGui.QApplication.translate("MainWindow", "Search Backward", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBtn.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceBtn.setText(QtGui.QApplication.translate("MainWindow", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Build.setText(QtGui.QApplication.translate("MainWindow", "&Build", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Build.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("MainWindow", "&Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clean.setText(QtGui.QApplication.translate("MainWindow", "&Clean", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Project.setText(QtGui.QApplication.translate("MainWindow", "&Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_Project.setText(QtGui.QApplication.translate("MainWindow", "&New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Upload.setText(QtGui.QApplication.translate("MainWindow", "&Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Upload.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Serial_Monitor.setText(QtGui.QApplication.translate("MainWindow", "&Serial Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Serial_Monitor.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Search.setText(QtGui.QApplication.translate("MainWindow", "&Search", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Search.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))

from projecttree import ProjectTree
import resource_rc
